# Generated by Django 2.1.2 on 2018-10-26 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
